#!/usr/bin/env python3
"""
AI Code Review using Claude API.

Reviews git diff and provides feedback on:
- Security vulnerabilities
- Performance issues
- Code smells
- Missing tests
- Architectural violations
"""

import os
import subprocess
import sys

try:
    import anthropic
except ImportError:
    print("❌ anthropic package not installed. Run: pip install anthropic")
    sys.exit(1)


def get_diff() -> str:
    """Get git diff for current branch vs develop"""
    try:
        result = subprocess.run(
            ["git", "diff", "origin/develop...HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout
    except subprocess.CalledProcessError as e:
        print(f"❌ Error getting git diff: {e}")
        return ""


def review_with_claude(diff: str) -> str:
    """Send diff to Claude for review"""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("⚠️  ANTHROPIC_API_KEY not set. Skipping AI review.")
        return "AI review skipped (no API key)"

    client = anthropic.Anthropic(api_key=api_key)

    prompt = f"""You are a senior software engineer reviewing code changes.

Review the following git diff and provide specific, actionable feedback on:

1. **Security**: Look for SQL injection, XSS, hardcoded secrets, insecure auth, etc.
2. **Performance**: Identify N+1 queries, unnecessary loops, inefficient algorithms
3. **Code Quality**: Find code smells, violations of DRY/SOLID, poor naming
4. **Testing**: Check if new code has tests, if tests cover edge cases
5. **Architecture**: Verify layer separation, no circular dependencies, proper DI

Format your response as:

## 🔐 Security Issues
- [Issue and fix suggestion]

## ⚡ Performance Concerns
- [Issue and optimization suggestion]

## 🧹 Code Quality
- [Issue and improvement suggestion]

## 🧪 Testing Gaps
- [Missing tests or edge cases]

## 🏗️ Architecture Notes
- [Architectural concerns]

## ✅ Positive Observations
- [Good practices worth noting]

Be concise and focus on HIGH-PRIORITY issues. If a section has no issues, write "None found."

---

Diff:
```diff
{diff[:15000]}  # Limit to ~15k chars to stay within context
```
"""

    try:
        message = client.messages.create(
            model="claude-sonnet-4-5",
            max_tokens=4000,
            messages=[{"role": "user", "content": prompt}],
        )
        return message.content[0].text
    except Exception as e:
        print(f"❌ Error calling Claude API: {e}")
        return f"AI review failed: {str(e)}"


def main():
    print("🤖 Running AI Code Review...")
    print()

    diff = get_diff()

    if not diff:
        print("ℹ️  No changes to review.")
        with open("ai_review_output.md", "w") as f:
            f.write("## AI Code Review\n\nNo changes to review.")
        return

    print(f"📊 Analyzing {len(diff)} characters of changes...")
    print()

    review = review_with_claude(diff)

    print(review)
    print()

    # Save for GitHub comment
    with open("ai_review_output.md", "w") as f:
        f.write("## 🤖 AI Code Review\n\n")
        f.write(review)
        f.write("\n\n---\n*Generated by Claude Sonnet 4.5*")

    print("✅ AI review complete! Output saved to ai_review_output.md")


if __name__ == "__main__":
    main()
