#!/usr/bin/env python3
"""
Generate TESTING_STATUS.md from pytest results.

Usage:
    python scripts/generate_testing_status.py --test-report test-report.json --coverage-report coverage.json --output docs/.auto-generated/status/TESTING_STATUS.md
"""

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


def parse_test_report(report_path):
    """Parse pytest JSON report."""
    if not Path(report_path).exists():
        return {
            "total": 0,
            "passed": 0,
            "failed": 0,
            "errors": 0,
            "skipped": 0,
            "duration": 0,
        }

    with open(report_path) as f:
        data = json.load(f)

    summary = data.get("summary", {})

    return {
        "total": summary.get("total", 0),
        "passed": summary.get("passed", 0),
        "failed": summary.get("failed", 0),
        "errors": summary.get("error", 0),
        "skipped": summary.get("skipped", 0),
        "duration": data.get("duration", 0),
    }


def parse_coverage_report(coverage_path):
    """Parse coverage JSON report."""
    if not Path(coverage_path).exists():
        return None

    with open(coverage_path) as f:
        data = json.load(f)

    totals = data.get("totals", {})

    return {
        "percent_covered": round(totals.get("percent_covered", 0), 2),
        "num_statements": totals.get("num_statements", 0),
        "missing_lines": totals.get("missing_lines", 0),
        "covered_lines": totals.get("covered_lines", 0),
    }


def generate_testing_status_md(output_path, test_report_path, coverage_report_path):
    """Generate TESTING_STATUS.md file."""
    test_data = parse_test_report(test_report_path)
    coverage_data = parse_coverage_report(coverage_report_path)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    # Calculate pass rate
    pass_rate = 0
    if test_data["total"] > 0:
        pass_rate = round((test_data["passed"] / test_data["total"]) * 100, 1)

    # Determine health status
    if test_data["failed"] == 0 and test_data["errors"] == 0:
        health_emoji = "✅"
        health_status = "Passing"
    elif test_data["failed"] > 5 or test_data["errors"] > 0:
        health_emoji = "🔴"
        health_status = "Failing"
    else:
        health_emoji = "⚠️"
        health_status = "Degraded"

    content = f"""# Testing Status

**Last Run:** {now}

## Summary
- **Total Tests:** {test_data["total"]}
- **Passed:** {test_data["passed"]}
- **Failed:** {test_data["failed"]}
- **Errors:** {test_data["errors"]}
- **Skipped:** {test_data["skipped"]}
- **Pass Rate:** {pass_rate}%
- **Duration:** {round(test_data["duration"], 1)}s

## Coverage Report
"""

    if coverage_data:
        content += f"""- **Coverage:** {coverage_data["percent_covered"]}%
- **Total Statements:** {coverage_data["num_statements"]}
- **Covered Lines:** {coverage_data["covered_lines"]}
- **Missing Lines:** {coverage_data["missing_lines"]}

See `htmlcov/index.html` for detailed report.
"""
    else:
        content += """Coverage data not available. Run `pytest --cov` to generate.
"""

    content += f"""
## Test Suite Health
{health_emoji} {health_status}

---

*This file is auto-generated. Do not edit manually.*
*Generated by: `scripts/generate_testing_status.py`*
"""

    # Write to file
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(content)

    print(f"✅ Generated: {output_path}")
    print(f"   Tests: {test_data['passed']}/{test_data['total']} passed")
    print(f"   Pass Rate: {pass_rate}%")
    if coverage_data:
        print(f"   Coverage: {coverage_data['percent_covered']}%")


def main():
    parser = argparse.ArgumentParser(description="Generate TESTING_STATUS.md")
    parser.add_argument(
        "--test-report", default="test-report.json", help="pytest JSON report file"
    )
    parser.add_argument(
        "--coverage-report", default="coverage.json", help="coverage JSON report file"
    )
    parser.add_argument(
        "--output",
        default="docs/.auto-generated/status/TESTING_STATUS.md",
        help="Output file path",
    )

    args = parser.parse_args()

    generate_testing_status_md(args.output, args.test_report, args.coverage_report)


if __name__ == "__main__":
    main()
