"""Centralized enumerations for RAE-core.

Provides type-safe constants for memory layers, content types, and formats.
Used for strict typing and preparation for Rust traits/enums.
"""

from enum import Enum


class MemoryLayer(str, Enum):
    """Memory layer enumeration."""

    SENSORY = "sensory"
    WORKING = "working"
    EPISODIC = "episodic"
    SEMANTIC = "semantic"
    REFLECTIVE = "reflective"


class MemoryType(str, Enum):
    """Type of memory content."""

    TEXT = "text"
    CODE = "code"
    IMAGE = "image"
    DOCUMENT = "document"
    CONVERSATION = "conversation"
    REFLECTION = "reflection"
    ENTITY = "entity"
    RELATIONSHIP = "relationship"


class ContextFormat(str, Enum):
    """Format types for context assembly."""

    CONVERSATIONAL = "conversational"
    STRUCTURED = "structured"
    MINIMAL = "minimal"
    DETAILED = "detailed"


class DistanceMetric(str, Enum):
    """Distance metrics for vector search."""

    COSINE = "Cosine"
    EUCLID = "Euclid"
    DOT = "Dot"


class ReflectionType(str, Enum):
    """Types of reflections generated by the system."""

    CONSOLIDATION = "consolidation"
    PATTERN = "pattern"
    ANOMALY = "anomaly"
    META = "meta"


class InformationClass(str, Enum):
    """Information classification per ISO 27000."""

    PUBLIC = "public"
    INTERNAL = "internal"
    CONFIDENTIAL = "confidential"
    RESTRICTED = "restricted"


class OperationRiskLevel(str, Enum):
    """Risk level for AI operations per ISO 42001."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    NONE = "none"
